import os
from datetime import datetime
from typing import Dict, Any, List, Optional
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from app.config import settings

class SupervisoryReportGenerator:
    @staticmethod
    def generate_html_preview(report_type: str, title: str, entity_name: str, summary: str, content: Dict[str, Any]) -> str:
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{title}</title>
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0B1120; color: #F1F5F9; padding: 40px; }}
                .container {{ max-width: 900px; margin: 0 auto; background: #0F172A; border: 1px solid #1E293B; border-radius: 8px; padding: 32px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }}
                .header {{ border-bottom: 2px solid #0284C7; padding-bottom: 16px; margin-bottom: 24px; }}
                .badge {{ background: #0284C7; color: white; padding: 4px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; text-transform: uppercase; }}
                h1 {{ color: #38BDF8; font-size: 24px; margin: 8px 0; }}
                .meta {{ color: #94A3B8; font-size: 13px; }}
                .summary {{ background: #1E293B; border-left: 4px solid #38BDF8; padding: 14px; margin: 20px 0; border-radius: 0 4px 4px 0; }}
                .section-title {{ color: #22D3EE; font-size: 18px; margin-top: 24px; border-bottom: 1px solid #334155; padding-bottom: 6px; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 14px; }}
                th, td {{ border: 1px solid #334155; padding: 10px; text-align: left; }}
                th {{ background: #1E293B; color: #38BDF8; }}
                .critical {{ color: #EF4444; font-weight: bold; }}
                .high {{ color: #F97316; font-weight: bold; }}
                .footer {{ margin-top: 40px; border-top: 1px solid #334155; padding-top: 16px; font-size: 12px; color: #64748B; text-align: center; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <span class="badge">{report_type}</span>
                    <h1>{title}</h1>
                    <div class="meta">Subject Entity: <strong>{entity_name}</strong> | Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')} | Classification: CONFIDENTIAL // NCIIPC</div>
                </div>
                <div class="summary">
                    <strong>Executive Supervisory Summary:</strong><br>
                    {summary}
                </div>
                <div>
                    <h3 class="section-title">Key Operational Findings & Evidence</h3>
        """

        findings = content.get("findings", [])
        if findings:
            html += """<table>
                <thead>
                    <tr><th>Rule ID</th><th>Domain</th><th>Severity</th><th>Description</th></tr>
                </thead>
                <tbody>"""
            for f in findings:
                sev_class = "critical" if f.get("severity") == "Critical" else "high"
                html += f"""<tr>
                    <td><code>{f.get('rule_id')}</code></td>
                    <td>{f.get('module')}</td>
                    <td class="{sev_class}">{f.get('severity')}</td>
                    <td>{f.get('explanation')}</td>
                </tr>"""
            html += "</tbody></table>"
        else:
            html += "<p>No critical non-compliance findings recorded for this review cycle.</p>"

        metrics = content.get("metrics", {})
        if metrics:
            html += "<h3 class=\"section-title\">Supervisory Metric Breakdown</h3><table><thead><tr><th>Metric</th><th>Score / Value</th></tr></thead><tbody>"
            for k, v in metrics.items():
                html += f"<tr><td>{k.replace('_', ' ').title()}</td><td><strong>{v}</strong></td></tr>"
            html += "</tbody></table>"

        html += """
                <div class="footer">
                    NATIONAL CRITICAL INFORMATION INFRASTRUCTURE PROTECTION CENTRE (NCIIPC)<br>
                    Official Supervisory Audit Document &bull; Generated by SAT-SA Supervisory Engine
                </div>
            </div>
        </body>
        </html>
        """
        return html

    @staticmethod
    def generate_pdf(report_id: str, title: str, entity_name: str, summary: str, content: Dict[str, Any]) -> str:
        pdf_filename = f"{report_id}.pdf"
        filepath = os.path.join(settings.REPORT_DIR, pdf_filename)

        doc = SimpleDocTemplate(filepath, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            name='ReportTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#0F172A'),
            spaceAfter=10
        )
        subtitle_style = ParagraphStyle(
            name='ReportSubTitle',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#475569'),
            spaceAfter=15
        )
        body_style = ParagraphStyle(
            name='ReportBody',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=10
        )

        elements = []
        elements.append(Paragraph(title, title_style))
        elements.append(Paragraph(f"Subject: {entity_name} | Generated: {datetime.utcnow().strftime('%Y-%m-%d')} | NCIIPC Supervisory System", subtitle_style))
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(f"<b>Executive Summary:</b> {summary}", body_style))
        elements.append(Spacer(1, 15))

        # Table of findings
        findings = content.get("findings", [])
        if findings:
            table_data = [["Rule ID", "Domain", "Severity", "Finding Description"]]
            for f in findings[:15]:
                table_data.append([
                    f.get("rule_id", ""),
                    f.get("module", ""),
                    f.get("severity", ""),
                    f.get("explanation", "")[:80] + "..."
                ])

            t = Table(table_data, colWidths=[80, 80, 70, 300])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0284C7')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
            ]))
            elements.append(t)

        doc.build(elements)
        return f"/api/reports/download/{pdf_filename}"

    @staticmethod
    def generate_docx(report_id: str, title: str, entity_name: str, summary: str, content: Dict[str, Any]) -> str:
        docx_filename = f"{report_id}.docx"
        filepath = os.path.join(settings.REPORT_DIR, docx_filename)

        doc = Document()
        # Title
        p_title = doc.add_heading(title, level=0)
        p_title.runs[0].font.color.rgb = RGBColor(11, 17, 32)
        
        doc.add_paragraph(f"Entity: {entity_name} | Date: {datetime.utcnow().strftime('%Y-%m-%d')} | Air-Gapped Supervisory Evaluation")
        doc.add_heading('Executive Supervisory Summary', level=1)
        doc.add_paragraph(summary)

        doc.add_heading('Key Non-Compliance Observations', level=1)
        findings = content.get("findings", [])
        if findings:
            table = doc.add_table(rows=1, cols=4)
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Rule ID'
            hdr_cells[1].text = 'Domain'
            hdr_cells[2].text = 'Severity'
            hdr_cells[3].text = 'Explanation'

            for f in findings:
                row_cells = table.add_row().cells
                row_cells[0].text = str(f.get("rule_id", ""))
                row_cells[1].text = str(f.get("module", ""))
                row_cells[2].text = str(f.get("severity", ""))
                row_cells[3].text = str(f.get("explanation", ""))

        doc.save(filepath)
        return f"/api/reports/download/{docx_filename}"
